app = "resonance"
primary_region = "ord"
kill_signal = "SIGTERM"
kill_timeout = 120
console_command = "bun run boot"
swap_size_mb = 512

[build]
image = "e03bcd44875e206ddaa39eb3d750ce6b"


[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0

[http_service.concurrency]
type = "requests"
soft_limit = 200
hard_limit = 250